version: '3.8'
services:
  minio:
    image: quay.io/minio/minio
    container_name: finbridge-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  postgres:
    image: postgres:18
    container_name: htt
    ports:
      - "5440:5432"
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: local
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  minio_data:
  postgres_data:
